name: Working Dir and Shells
on: [push]

jobs:
  display-wd-info:
    runs-on: ubuntu-latest

    steps:
      - name: Display Working Directory & List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: Change Working Directory
        working-directory: /home/runner
        run: pwd

  display-wd-info-windows:
    runs-on: windows-latest
    steps:
      - name: Display Working Directory & List Files
        run: |
          Get-Location
          dir
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
